# Copyright (C) 2026 Rootiest
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Generates ~/.local/bin/paru and ~/.local/bin/yay on first run (and on
# version bump) for whichever of them is installed. Each wrapper runs its
# package manager in a PTY so progress bars are preserved, renders the
# captured animation to a clean static log (via
# scripts/clean_progress_log.py), and prunes old logs.

# COMPONENT
#   site paru-autoexec: autoexec/pkg-wrappers
#   site paru-logging: logging/pkg-logs
#   site yay-autoexec: autoexec/pkg-wrappers
#   site yay-logging: logging/pkg-logs

# Defines nothing; its only effect is generating the wrappers, an
# idempotent write every interactive session already performs.
status is-interactive; or return

set -l _pkg_wrapper_version 8

# Every early exit below is `continue`, not `return`: a guard that skips
# paru must not skip yay.
for pm in paru yay
    # Auto-generating a wrapper in ~/.local/bin is opinionated (C2 auto-exec).
    # Wrapper generation is also gated by C5 (Logging & Capture).
    __fish_config_op_enabled (status basename) $pm-autoexec; or continue

    set -l wrapper "$HOME/.local/bin/$pm"

    # C5 — Logging & Capture: remove generated wrapper and skip when logging is off
    if not __fish_config_op_enabled (status basename) $pm-logging
        if test -f $wrapper
            and grep -q "# $pm-wrapper-version:" $wrapper 2>/dev/null
            rm -f $wrapper
        end
        continue
    end

    # Resolve the real binary, skipping our own shim (never /usr/bin-assumed).
    set -l real (__fish_real_command $pm)

    # Skip if the real binary isn't present
    test -x "$real"; or continue

    # Skip if the wrapper already exists at the expected version
    if test -f $wrapper
        and grep -q "# $pm-wrapper-version: $_pkg_wrapper_version" $wrapper 2>/dev/null
        continue
    end

    mkdir -p (dirname $wrapper)

    printf '%s\n' \
        '#!/usr/bin/env bash' \
        "# $pm-wrapper-version: $_pkg_wrapper_version" \
        '# Auto-generated by conf.d/pkg-wrappers.fish — do not edit by hand.' \
        "# Runs $pm in a PTY via script(1) so progress bars are preserved on screen," \
        '# then renders the captured terminal animation to a clean static log.' \
        '' \
        'log_dir="${SCROLLBACK_HISTORY_DIR:-$HOME/.terminal_history}"' \
        '# Logs can hold anything the package manager printed: keep them private' \
        '# (dir 700, files 600), tightening a laxer dir from an older version once.' \
        'mkdir -p -m 700 "$log_dir"' \
        'if [[ "$(stat -L -c %a "$log_dir" 2>/dev/null)" != 700 ]]; then' \
        '    chmod 700 "$log_dir" && find "$log_dir/" -maxdepth 1 -type f -exec chmod 600 -- {} +' \
        fi \
        'log_file="$log_dir/'$pm'_$(date +%Y-%m-%d_%H-%M-%S).log"' \
        '' \
        '# Build a safely-quoted command string for script(1).' \
        "# script(1) allocates a PTY so $pm detects a real terminal and shows progress." \
        "cmd_str=\"$real\"" \
        'for arg in "$@"; do' \
        '    cmd_str+=" $(printf '"'"'%q'"'"' "$arg")"' \
        done \
        '( umask 077; : >"$log_file" )' \
        'script -q -e -c "$cmd_str" "$log_file"' \
        'exit_code=$?' \
        '' \
        '# Render the captured terminal animation (progress bars repaint in place via' \
        '# cursor moves) down to its final static frame, preserving ANSI color. Falls' \
        '# back to dropping only the script(1) header/footer when python3 is missing.' \
        'cleaner="${XDG_CONFIG_HOME:-$HOME/.config}/fish/scripts/clean_progress_log.py"' \
        'if command -v python3 >/dev/null 2>&1 && [[ -f "$cleaner" ]]; then' \
        '    python3 "$cleaner" < "$log_file" > "${log_file}.tmp" 2>/dev/null && mv "${log_file}.tmp" "$log_file" || rm -f "${log_file}.tmp"' \
        else \
        '    sed -i "/^Script \(started\|done\) on /d" "$log_file" 2>/dev/null || true' \
        fi \
        'chmod 600 "$log_file" 2>/dev/null' \
        '' \
        'max_files="${SCROLLBACK_HISTORY_MAX_FILES:-100}"' \
        'mapfile -t logs < <(ls -1t "$log_dir"/'$pm'_*.log 2>/dev/null)' \
        'excess=$(( ${#logs[@]} - max_files ))' \
        'for (( i = ${#logs[@]} - 1; i >= ${#logs[@]} - excess && i >= 0; i-- )); do' \
        '    rm -f "${logs[$i]}"' \
        done \
        '' \
        'exit $exit_code' >$wrapper

    chmod +x $wrapper
end
