# Copyright (C) 2026 Rootiest
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Generates ~/.local/bin/yay on first run (and on version bump) when
# /usr/bin/yay is installed. The wrapper tees yay output to a
# timestamped log file and prunes old logs, mirroring smart_exit behavior.

# Auto-generating a wrapper in ~/.local/bin is opinionated (C2 auto-exec).
# Wrapper generation is also gated by C5 (Logging & Capture).
__fish_config_op_enabled __fish_config_op_autoexec; or return

# C5 — Logging & Capture: remove generated wrapper and skip when logging is off
if not __fish_config_op_enabled __fish_config_op_logging
    if test -f "$HOME/.local/bin/yay"
        and grep -q "# yay-wrapper-version:" "$HOME/.local/bin/yay" 2>/dev/null
        rm -f "$HOME/.local/bin/yay"
    end
    return
end

set -l _yay_real /usr/bin/yay
set -l _yay_wrapper "$HOME/.local/bin/yay"
set -l _yay_wrapper_version 2

# Skip entirely if the real yay binary isn't present
test -x $_yay_real; or return

# Check if wrapper already exists at the expected version
if test -f $_yay_wrapper
    and grep -q "# yay-wrapper-version: $_yay_wrapper_version" $_yay_wrapper 2>/dev/null
    set --erase _yay_real _yay_wrapper _yay_wrapper_version
    return
end

mkdir -p (dirname $_yay_wrapper)

printf '%s\n' \
    '#!/usr/bin/env bash' \
    "# yay-wrapper-version: $_yay_wrapper_version" \
    '# Auto-generated by conf.d/yay-wrapper.fish — do not edit by hand.' \
    '# Runs yay in a PTY via script(1) so progress bars are preserved,' \
    '# then strips escape sequences from the captured log file.' \
    '' \
    'log_dir="${SCROLLBACK_HISTORY_DIR:-$HOME/.terminal_history}"' \
    'mkdir -p "$log_dir"' \
    'log_file="$log_dir/yay_$(date +%Y-%m-%d_%H-%M-%S).log"' \
    '' \
    '# Build a safely-quoted command string for script(1).' \
    '# script(1) allocates a PTY so yay detects a real terminal and shows progress.' \
    'cmd_str="/usr/bin/yay"' \
    'for arg in "$@"; do' \
    '    cmd_str+=" $(printf '"'"'%q'"'"' "$arg")"' \
    'done' \
    'script -q -e -c "$cmd_str" "$log_file"' \
    'exit_code=$?' \
    '' \
    '# Strip ANSI escape sequences and carriage returns for readable plain-text logs.' \
    'sed -i '"'"'s/\x1b\[[0-9;?]*[a-zA-Z]//g; s/\r//g'"'"' "$log_file" 2>/dev/null || true' \
    '' \
    'max_files="${SCROLLBACK_HISTORY_MAX_FILES:-100}"' \
    'mapfile -t logs < <(ls -1t "$log_dir"/yay_*.log 2>/dev/null)' \
    'excess=$(( ${#logs[@]} - max_files ))' \
    'for (( i = ${#logs[@]} - 1; i >= ${#logs[@]} - excess && i >= 0; i-- )); do' \
    '    rm -f "${logs[$i]}"' \
    'done' \
    '' \
    'exit $exit_code' \
    > $_yay_wrapper

chmod +x $_yay_wrapper

set --erase _yay_real _yay_wrapper _yay_wrapper_version
