# Copyright (C) 2026 Rootiest
# SPDX-License-Identifier: AGPL-3.0-or-later

# Completions for `bd`, generated by the installed binary so they always
# match its version instead of being vendored here. The script is loaded
# once per shell session, on the first completion attempt.
#
# bd skips its database setup for the completion commands, so this is safe
# to run in any directory.

type -q bd; or return
bd completion fish | source
