# Copyright (C) 2026 Rootiest
# SPDX-License-Identifier: AGPL-3.0-or-later

# Completions for `copilot`, generated by the installed binary so they
# always match its version instead of being vendored here. The script is
# loaded once per shell session, on the first completion attempt.

type -q copilot; or return
copilot completion fish | source
