# Copyright (C) 2026 Rootiest
# SPDX-License-Identifier: AGPL-3.0-or-later

# Completions for `deadbranch`, generated by the installed binary so they
# always match its version instead of being vendored here. The script is
# loaded once per shell session, on the first completion attempt.
#
# Note the plural subcommand: `deadbranch completions fish`.

type -q deadbranch; or return
deadbranch completions fish | source
