# Copyright (C) 2026 Rootiest
# SPDX-License-Identifier: AGPL-3.0-or-later

# Completions for `tailscale`, generated by the installed binary so they
# always match its version. Only Arch's package ships a fish completion;
# the official deb/rpm packages (pkgs.tailscale.com) do not.

type -q tailscale; or return
tailscale completion fish | source
